export enum UserType {
  USER = 'USER',
  ADMIN = 'ADMIN',
  STAFF = 'STAFF',
}

export enum Permission {
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_CONFIRM_STAFF = 'USER_CONFIRM_STAFF',

  PROFILE_VIEW_OWN = 'PROFILE_VIEW_OWN',
  PROFILE_UPDATE_OWN = 'PROFILE_UPDATE_OWN',

  BOOKING_VIEW_OWN = 'BOOKING_VIEW_OWN',
  BOOKING_VIEW_ALL = 'BOOKING_VIEW_ALL',
  BOOKING_CREATE = 'BOOKING_CREATE',
  BOOKING_CREATE_FOR_CLIENT = 'BOOKING_CREATE_FOR_CLIENT',
  BOOKING_UPDATE = 'BOOKING_UPDATE',
  BOOKING_UPDATE_STATUS = 'BOOKING_UPDATE_STATUS',
  BOOKING_DELETE = 'BOOKING_DELETE',

  SERVICE_VIEW = 'SERVICE_VIEW',
  SERVICE_CREATE = 'SERVICE_CREATE',
  SERVICE_UPDATE = 'SERVICE_UPDATE',
  SERVICE_DELETE = 'SERVICE_DELETE',

  PAYMENT_VIEW_OWN = 'PAYMENT_VIEW_OWN',
  PAYMENT_VIEW_ALL = 'PAYMENT_VIEW_ALL',
  PAYMENT_CREATE = 'PAYMENT_CREATE',
  PAYMENT_UPDATE = 'PAYMENT_UPDATE',
  PAYMENT_DELETE = 'PAYMENT_DELETE',
  PAYMENT_PROCESS = 'PAYMENT_PROCESS',

  INVOICE_VIEW_OWN = 'INVOICE_VIEW_OWN',
  INVOICE_VIEW_ALL = 'INVOICE_VIEW_ALL',
  INVOICE_CREATE = 'INVOICE_CREATE',
  INVOICE_UPDATE = 'INVOICE_UPDATE',
  INVOICE_DELETE = 'INVOICE_DELETE',
  INVOICE_GENERATE = 'INVOICE_GENERATE',

  RECEIPT_VIEW_OWN = 'RECEIPT_VIEW_OWN',
  RECEIPT_VIEW_ALL = 'RECEIPT_VIEW_ALL',
  RECEIPT_CREATE = 'RECEIPT_CREATE',
  RECEIPT_UPDATE = 'RECEIPT_UPDATE',
  RECEIPT_DELETE = 'RECEIPT_DELETE',
  RECEIPT_GENERATE = 'RECEIPT_GENERATE',

  TESTIMONIAL_VIEW = 'TESTIMONIAL_VIEW',
  TESTIMONIAL_CREATE = 'TESTIMONIAL_CREATE',
  TESTIMONIAL_UPDATE = 'TESTIMONIAL_UPDATE',
  TESTIMONIAL_DELETE = 'TESTIMONIAL_DELETE',
  TESTIMONIAL_MANAGE = 'TESTIMONIAL_MANAGE',

  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
  REPORTS_VIEW = 'REPORTS_VIEW',
  REPORTS_GENERATE = 'REPORTS_GENERATE',
  REPORTS_EXPORT = 'REPORTS_EXPORT',

  PDF_GENERATE_INVOICE = 'PDF_GENERATE_INVOICE',
  PDF_GENERATE_RECEIPT = 'PDF_GENERATE_RECEIPT',
  PDF_GENERATE_REPORT = 'PDF_GENERATE_REPORT',

  SETTINGS_UPDATE = 'SETTINGS_UPDATE',

  STAFF_MANAGE = 'STAFF_MANAGE',
  STAFF_VIEW = 'STAFF_VIEW',
  STAFF_CREATE = 'STAFF_CREATE',
  STAFF_UPDATE = 'STAFF_UPDATE',
  STAFF_DELETE = 'STAFF_DELETE',

  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  PERMISSION_ASSIGN = 'PERMISSION_ASSIGN',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK = 'BANK',
  WAVE = 'WAVE',
  APS = 'APS',
  YONNA = 'YONNA',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum InvoiceStatus {
  UNPAID = 'UNPAID',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  OVERDUE = 'OVERDUE',
}
