// types/permissions.ts

export enum Permission {
  // User permissions
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_CONFIRM_STAFF = 'USER_CONFIRM_STAFF',

  // Profile permissions
  PROFILE_VIEW_OWN = 'PROFILE_VIEW_OWN',
  PROFILE_UPDATE_OWN = 'PROFILE_UPDATE_OWN',

  // Booking permissions
  BOOKING_CREATE_FOR_CLIENT = 'BOOKING_CREATE_FOR_CLIENT',
  BOOKING_VIEW_OWN = 'BOOKING_VIEW_OWN',
  BOOKING_VIEW_ALL = 'BOOKING_VIEW_ALL',
  BOOKING_CREATE = 'BOOKING_CREATE',
  BOOKING_UPDATE = 'BOOKING_UPDATE',
  BOOKING_UPDATE_OWN = 'BOOKING_UPDATE_OWN',
  BOOKING_UPDATE_STATUS = 'BOOKING_UPDATE_STATUS',
  BOOKING_DELETE = 'BOOKING_DELETE',

  // Service permissions
  SERVICE_VIEW = 'SERVICE_VIEW',
  SERVICE_CREATE = 'SERVICE_CREATE',
  SERVICE_UPDATE = 'SERVICE_UPDATE',
  SERVICE_DELETE = 'SERVICE_DELETE',

  // Payment permissions
  PAYMENT_VIEW_OWN = 'PAYMENT_VIEW_OWN',
  PAYMENT_VIEW_ALL = 'PAYMENT_VIEW_ALL',
  PAYMENT_CREATE = 'PAYMENT_CREATE',
  PAYMENT_UPDATE = 'PAYMENT_UPDATE',
  PAYMENT_DELETE = 'PAYMENT_DELETE',
  PAYMENT_PROCESS = 'PAYMENT_PROCESS',

  // Invoice permissions
  INVOICE_VIEW_OWN = 'INVOICE_VIEW_OWN',
  INVOICE_VIEW_ALL = 'INVOICE_VIEW_ALL',
  INVOICE_CREATE = 'INVOICE_CREATE',
  INVOICE_UPDATE = 'INVOICE_UPDATE',
  INVOICE_DELETE = 'INVOICE_DELETE',
  INVOICE_GENERATE = 'INVOICE_GENERATE',

  // Receipt permissions
  RECEIPT_VIEW_OWN = 'RECEIPT_VIEW_OWN',
  RECEIPT_VIEW_ALL = 'RECEIPT_VIEW_ALL',
  RECEIPT_CREATE = 'RECEIPT_CREATE',
  RECEIPT_UPDATE = 'RECEIPT_UPDATE',
  RECEIPT_DELETE = 'RECEIPT_DELETE',
  RECEIPT_GENERATE = 'RECEIPT_GENERATE',

  // Testimonial permissions
  TESTIMONIAL_VIEW = 'TESTIMONIAL_VIEW',
  TESTIMONIAL_CREATE = 'TESTIMONIAL_CREATE',
  TESTIMONIAL_UPDATE = 'TESTIMONIAL_UPDATE',
  TESTIMONIAL_DELETE = 'TESTIMONIAL_DELETE',
  TESTIMONIAL_MANAGE = 'TESTIMONIAL_MANAGE',

  // Analytics and Reports permissions
  ANALYTICS_VIEW = 'ANALYTICS_VIEW',
  REPORTS_VIEW = 'REPORTS_VIEW',
  REPORTS_GENERATE = 'REPORTS_GENERATE',
  REPORTS_EXPORT = 'REPORTS_EXPORT',

  // PDF and Document generation permissions
  PDF_GENERATE_INVOICE = 'PDF_GENERATE_INVOICE',
  PDF_GENERATE_RECEIPT = 'PDF_GENERATE_RECEIPT',
  PDF_GENERATE_REPORT = 'PDF_GENERATE_REPORT',

  // Settings permissions
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',

  // Staff management permissions
  STAFF_MANAGE = 'STAFF_MANAGE',
  STAFF_VIEW = 'STAFF_VIEW',
  STAFF_CREATE = 'STAFF_CREATE',
  STAFF_UPDATE = 'STAFF_UPDATE',
  STAFF_DELETE = 'STAFF_DELETE',

  // Role and permission management
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  PERMISSION_ASSIGN = 'PERMISSION_ASSIGN',
}

// Type for permission string
export type PermissionString = `${Permission}`;

// Array of all permissions
export const ALL_PERMISSIONS = Object.values(Permission);
